{
 "title": "Cloudflare Tunnel",
 "tags": [
  "cloudflare",
  "cloudflared",
  "tunnel"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Connector Metrics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"cloudflared\"}",
     "legendFormat": "Metrics"
    }
   ]
  },
  {
   "title": "Edge Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cloudflared_tunnel_ha_connections)",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cloudflared_tunnel_total_requests[5m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Responses by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(cloudflared_tunnel_response_by_code[5m]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Tunnel Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(cloudflared_tunnel_request_errors[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}